<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Affectation extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Affectation_model');
    } 

    /*
     * Listing of affectations
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('affectation/index?');
        $config['total_rows'] = $this->Affectation_model->get_all_affectations_count();
        $this->pagination->initialize($config);

        $data['affectations'] = $this->Affectation_model->get_all_affectations($params);
        
        $data['_view'] = 'affectation/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new affectation
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('Agent_sid','Agent Sid','required');
		$this->form_validation->set_rules('DateAffectation','DateAffectation','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'Service_sid' => $this->input->post('Service_sid'),
				'Agent_sid' => $this->input->post('Agent_sid'),
				'DateAffectation' => $this->input->post('DateAffectation'),
				'DateAjout' =>  date('Y-m-d H:i:s'),
				'PosteOccupe' => $this->input->post('PosteOccupe'),
				'NomGouverneur' => $this->input->post('NomGouverneur'),
				'Objectif' => $this->input->post('Objectif'),
				'affec_observ' => $this->input->post('affec_observ'),
            );
            
            $affectation_id = $this->Affectation_model->add_affectation($params);
            redirect('affectation/index');
        }
        else
        {
			$this->load->model('Service_model');
			$data['all_services'] = $this->Service_model->get_all_services();

			$this->load->model('Agent_model');
			$data['all_agents'] = $this->Agent_model->get_all_agents();
            
            $data['_view'] = 'affectation/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a affectation
     */
    function edit($Affectation_id)
    {   
        // check if the affectation exists before trying to edit it
        $data['affectation'] = $this->Affectation_model->get_affectation($Affectation_id);
        
        if(isset($data['affectation']['Affectation_id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('Agent_sid','Agent Sid','required');
			$this->form_validation->set_rules('DateAffectation','DateAffectation','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'Service_sid' => $this->input->post('Service_sid'),
					'Agent_sid' => $this->input->post('Agent_sid'),
					'DateAffectation' => $this->input->post('DateAffectation'),
					
					'PosteOccupe' => $this->input->post('PosteOccupe'),
					'NomGouverneur' => $this->input->post('NomGouverneur'),
					'Objectif' => $this->input->post('Objectif'),
					'affec_observ' => $this->input->post('affec_observ'),
                );

                $this->Affectation_model->update_affectation($Affectation_id,$params);            
                redirect('affectation/index');
            }
            else
            {
				$this->load->model('Service_model');
				$data['all_services'] = $this->Service_model->get_all_services();

				$this->load->model('Agent_model');
				$data['all_agents'] = $this->Agent_model->get_all_agents();

                $data['_view'] = 'affectation/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The affectation you are trying to edit does not exist.');
    } 

    /*
     * Deleting affectation
     */
    function remove($Affectation_id)
    {
        $affectation = $this->Affectation_model->get_affectation($Affectation_id);

        // check if the affectation exists before trying to delete it
        if(isset($affectation['Affectation_id']))
        {
            $this->Affectation_model->delete_affectation($Affectation_id);
            redirect('affectation/index');
        }
        else
            show_error('The affectation you are trying to delete does not exist.');
    }
    
}
