<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Commune extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Commune_model');
    } 

    /*
     * Listing of communes
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('commune/index?');
        $config['total_rows'] = $this->Commune_model->get_all_communes_count();
        $this->pagination->initialize($config);

        $data['communes'] = $this->Commune_model->get_all_communes($params);
        
        $data['_view'] = 'commune/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new commune
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'NomCommune' => $this->input->post('NomCommune'),
				'NomOfficier' => $this->input->post('NomOfficier'),
				'AdresseBureau' => $this->input->post('AdresseBureau'),
            );
            
            $commune_id = $this->Commune_model->add_commune($params);
            redirect('commune/index');
        }
        else
        {            
            $data['_view'] = 'commune/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a commune
     */
    function edit($Commune_Id)
    {   
        // check if the commune exists before trying to edit it
        $data['commune'] = $this->Commune_model->get_commune($Commune_Id);
        
        if(isset($data['commune']['Commune_Id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'NomCommune' => $this->input->post('NomCommune'),
					'NomOfficier' => $this->input->post('NomOfficier'),
					'AdresseBureau' => $this->input->post('AdresseBureau'),
                );

                $this->Commune_model->update_commune($Commune_Id,$params);            
                redirect('commune/index');
            }
            else
            {
                $data['_view'] = 'commune/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The commune you are trying to edit does not exist.');
    } 

    /*
     * Deleting commune
     */
    function remove($Commune_Id)
    {
        $commune = $this->Commune_model->get_commune($Commune_Id);

        // check if the commune exists before trying to delete it
        if(isset($commune['Commune_Id']))
        {
            $this->Commune_model->delete_commune($Commune_Id);
            redirect('commune/index');
        }
        else
            show_error('The commune you are trying to delete does not exist.');
    }
    
}
