<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Piece extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Piece_model');
    } 

    /*
     * Listing of piece
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('piece/index?');
        $config['total_rows'] = $this->Piece_model->get_all_piece_count();
        $this->pagination->initialize($config);

        $data['piece'] = $this->Piece_model->get_all_piece($params);
        
        $data['_view'] = 'piece/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new piece
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'Matricule' => $this->input->post('Matricule'),
				'Date_Piece' => $this->input->post('Date_Piece'),
				'Nom_Piece' => $this->input->post('Nom_Piece'),
            );
            
            $piece_id = $this->Piece_model->add_piece($params);
            redirect('piece/index');
        }
        else
        {
			$this->load->model('Agent_model');
			$data['all_agents'] = $this->Agent_model->get_all_agents();
            
            $data['_view'] = 'piece/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a piece
     */
    function edit($Id_Piece)
    {   
        // check if the piece exists before trying to edit it
        $data['piece'] = $this->Piece_model->get_piece($Id_Piece);
        
        if(isset($data['piece']['Id_Piece']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'Matricule' => $this->input->post('Matricule'),
					'Date_Piece' => $this->input->post('Date_Piece'),
					'Nom_Piece' => $this->input->post('Nom_Piece'),
                );

                $this->Piece_model->update_piece($Id_Piece,$params);            
                redirect('piece/index');
            }
            else
            {
				$this->load->model('Agent_model');
				$data['all_agents'] = $this->Agent_model->get_all_agents();

                $data['_view'] = 'piece/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The piece you are trying to edit does not exist.');
    } 

    /*
     * Deleting piece
     */
    function remove($Id_Piece)
    {
        $piece = $this->Piece_model->get_piece($Id_Piece);

        // check if the piece exists before trying to delete it
        if(isset($piece['Id_Piece']))
        {
            $this->Piece_model->delete_piece($Id_Piece);
            redirect('piece/index');
        }
        else
            show_error('The piece you are trying to delete does not exist.');
    }
    
}
