<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Service extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Service_model');
    } 

    /*
     * Listing of services
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('service/index?');
        $config['total_rows'] = $this->Service_model->get_all_services_count();
        $this->pagination->initialize($config);

        $data['services'] = $this->Service_model->get_all_services($params);
        
        $data['_view'] = 'service/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new service
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('NomService','NomService','required');
		$this->form_validation->set_rules('NomResponsable','NomResponsable','required');
		$this->form_validation->set_rules('AdresseBureau','AdresseBureau','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'Commune_sid' => $this->input->post('Commune_sid'),
				'NomService' => $this->input->post('NomService'),
				'NomResponsable' => $this->input->post('NomResponsable'),
				'AdresseBureau' => $this->input->post('AdresseBureau'),
				'DateAjout' =>  date('Y-m-d H:i:s'),
            );
            
            $service_id = $this->Service_model->add_service($params);
            redirect('service/index');
        }
        else
        {
			$this->load->model('Commune_model');
			$data['all_communes'] = $this->Commune_model->get_all_communes();
            
            $data['_view'] = 'service/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a service
     */
    function edit($Service_id)
    {   
        // check if the service exists before trying to edit it
        $data['service'] = $this->Service_model->get_service($Service_id);
        
        if(isset($data['service']['Service_id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('NomService','NomService','required');
			$this->form_validation->set_rules('NomResponsable','NomResponsable','required');
			$this->form_validation->set_rules('AdresseBureau','AdresseBureau','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'Commune_sid' => $this->input->post('Commune_sid'),
					'NomService' => $this->input->post('NomService'),
					'NomResponsable' => $this->input->post('NomResponsable'),
					'AdresseBureau' => $this->input->post('AdresseBureau'),
					
                );

                $this->Service_model->update_service($Service_id,$params);            
                redirect('service/index');
            }
            else
            {
				$this->load->model('Commune_model');
				$data['all_communes'] = $this->Commune_model->get_all_communes();

                $data['_view'] = 'service/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The service you are trying to edit does not exist.');
    } 

    /*
     * Deleting service
     */
    function remove($Service_id)
    {
        $service = $this->Service_model->get_service($Service_id);

        // check if the service exists before trying to delete it
        if(isset($service['Service_id']))
        {
            $this->Service_model->delete_service($Service_id);
            redirect('service/index');
        }
        else
            show_error('The service you are trying to delete does not exist.');
    }
    
}
