<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Agent_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get agent by Agent_id
     */
    function get_agent($Agent_id)
    {
        return $this->db->get_where('tb_am_agents',array('Agent_id'=>$Agent_id))->row_array();
    }
    
    /*
     * Get all agents count
     */
    function get_all_agents_count()
    {
        $this->db->from('tb_am_agents');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all agents
     */
    function get_all_agents($params = array())
    {
        $this->db->order_by('Agent_id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('tb_am_agents')->result_array();
    }
        
    /*
     * function to add new agent
     */
    function add_agent($params)
    {
        $this->db->insert('tb_am_agents',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update agent
     */
    function update_agent($Agent_id,$params)
    {
        $this->db->where('Agent_id',$Agent_id);
        return $this->db->update('tb_am_agents',$params);
    }
    
    /*
     * function to delete agent
     */
    function delete_agent($Agent_id)
    {
        return $this->db->delete('tb_am_agents',array('Agent_id'=>$Agent_id));
    }
}
