<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Commune_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get commune by Commune_Id
     */
    function get_commune($Commune_Id)
    {
        return $this->db->get_where('tb_am_communes',array('Commune_Id'=>$Commune_Id))->row_array();
    }
    
    /*
     * Get all communes count
     */
    function get_all_communes_count()
    {
        $this->db->from('tb_am_communes');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all communes
     */
    function get_all_communes($params = array())
    {
        $this->db->order_by('Commune_Id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('tb_am_communes')->result_array();
    }
        
    /*
     * function to add new commune
     */
    function add_commune($params)
    {
        $this->db->insert('tb_am_communes',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update commune
     */
    function update_commune($Commune_Id,$params)
    {
        $this->db->where('Commune_Id',$Commune_Id);
        return $this->db->update('tb_am_communes',$params);
    }
    
    /*
     * function to delete commune
     */
    function delete_commune($Commune_Id)
    {
        return $this->db->delete('tb_am_communes',array('Commune_Id'=>$Commune_Id));
    }
}
