<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Demande_affectation_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get demande_affectation by Id_demande_affectation
     */
    function get_demande_affectation($Id_demande_affectation)
    {
        return $this->db->get_where('demande_affectation',array('Id_demande_affectation'=>$Id_demande_affectation))->row_array();
    }
    
    /*
     * Get all demande_affectation count
     */
    function get_all_demande_affectation_count()
    {
        $this->db->from('demande_affectation');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all demande_affectation
     */
    function get_all_demande_affectation($params = array())
    {
        $this->db->order_by('Id_demande_affectation', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('demande_affectation')->result_array();
    }
        
    /*
     * function to add new demande_affectation
     */
    function add_demande_affectation($params)
    {
        $this->db->insert('demande_affectation',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update demande_affectation
     */
    function update_demande_affectation($Id_demande_affectation,$params)
    {
        $this->db->where('Id_demande_affectation',$Id_demande_affectation);
        return $this->db->update('demande_affectation',$params);
    }
    
    /*
     * function to delete demande_affectation
     */
    function delete_demande_affectation($Id_demande_affectation)
    {
        return $this->db->delete('demande_affectation',array('Id_demande_affectation'=>$Id_demande_affectation));
    }
}
