<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Fiche_affectation_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get fiche_affectation by Id
     */
    function get_fiche_affectation($Id)
    {
        return $this->db->get_where('fiche_affectation',array('Id'=>$Id))->row_array();
    }
    
    /*
     * Get all fiche_affectation count
     */
    function get_all_fiche_affectation_count()
    {
        $this->db->from('fiche_affectation');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all fiche_affectation
     */
    function get_all_fiche_affectation($params = array())
    {
        $this->db->order_by('Id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('fiche_affectation')->result_array();
    }
        
    /*
     * function to add new fiche_affectation
     */
    function add_fiche_affectation($params)
    {
        $this->db->insert('fiche_affectation',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update fiche_affectation
     */
    function update_fiche_affectation($Id,$params)
    {
        $this->db->where('Id',$Id);
        return $this->db->update('fiche_affectation',$params);
    }
    
    /*
     * function to delete fiche_affectation
     */
    function delete_fiche_affectation($Id)
    {
        return $this->db->delete('fiche_affectation',array('Id'=>$Id));
    }
}
