<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Piece_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get piece by Id_Piece
     */
    function get_piece($Id_Piece)
    {
        return $this->db->get_where('piece',array('Id_Piece'=>$Id_Piece))->row_array();
    }
    
    /*
     * Get all piece count
     */
    function get_all_piece_count()
    {
        $this->db->from('piece');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all piece
     */
    function get_all_piece($params = array())
    {
        $this->db->order_by('Id_Piece', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('piece')->result_array();
    }
        
    /*
     * function to add new piece
     */
    function add_piece($params)
    {
        $this->db->insert('piece',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update piece
     */
    function update_piece($Id_Piece,$params)
    {
        $this->db->where('Id_Piece',$Id_Piece);
        return $this->db->update('piece',$params);
    }
    
    /*
     * function to delete piece
     */
    function delete_piece($Id_Piece)
    {
        return $this->db->delete('piece',array('Id_Piece'=>$Id_Piece));
    }
}
