<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Service_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get service by Service_id
     */
    function get_service($Service_id)
    {
        return $this->db->get_where('tb_am_services',array('Service_id'=>$Service_id))->row_array();
    }
    
    /*
     * Get all services count
     */
    function get_all_services_count()
    {
        $this->db->from('tb_am_services');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all services
     */
    function get_all_services($params = array())
    {
        $this->db->order_by('Service_id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('tb_am_services')->result_array();
    }
        
    /*
     * function to add new service
     */
    function add_service($params)
    {
        $this->db->insert('tb_am_services',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update service
     */
    function update_service($Service_id,$params)
    {
        $this->db->where('Service_id',$Service_id);
        return $this->db->update('tb_am_services',$params);
    }
    
    /*
     * function to delete service
     */
    function delete_service($Service_id)
    {
        return $this->db->delete('tb_am_services',array('Service_id'=>$Service_id));
    }
}
